"""creat

Revision ID: 0108e21e1e83
Revises: f3a4389e1113
Create Date: 2026-05-21 12:45:37.615405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0108e21e1e83'
down_revision: Union[str, None] = 'f3a4389e1113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deposit_intents', 'method',
               existing_type=mysql.ENUM('VIRTUAL_ACCOUNT', 'CARD', 'MOBILE_MONEY', 'USSD'),
               type_=sa.Enum('BANK_TRANSFER', 'CARD', 'MOBILE_MONEY', 'USSD', name='depositmethod'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deposit_intents', 'method',
               existing_type=sa.Enum('BANK_TRANSFER', 'CARD', 'MOBILE_MONEY', 'USSD', name='depositmethod'),
               type_=mysql.ENUM('VIRTUAL_ACCOUNT', 'CARD', 'MOBILE_MONEY', 'USSD'),
               existing_nullable=False)
    # ### end Alembic commands ###
