"""update withdrawal + wallet transaction flow

Revision ID: 0a9a5e2efb60
Revises: 0734df127a26
Create Date: 2026-05-22 16:24:15.149775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9a5e2efb60'
down_revision: Union[str, None] = '0734df127a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('wallet_id', sa.String(length=36), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'FUND_RELEASED', 'UNDER_REVIEW', 'CANCELLED', name='transactionstatus'), nullable=True),
    sa.Column('flutterwave_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_intents_reference'), 'withdrawal_intents', ['reference'], unique=True)
    op.create_index(op.f('ix_withdrawal_intents_user_id'), 'withdrawal_intents', ['user_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_intents_wallet_id'), 'withdrawal_intents', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_intents_wallet_id'), table_name='withdrawal_intents')
    op.drop_index(op.f('ix_withdrawal_intents_user_id'), table_name='withdrawal_intents')
    op.drop_index(op.f('ix_withdrawal_intents_reference'), table_name='withdrawal_intents')
    op.drop_table('withdrawal_intents')
    # ### end Alembic commands ###
