"""creating  settings

Revision ID: 29d0f8548438
Revises: 81289a9455e3
Create Date: 2026-09-25 21:25:49.351404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d0f8548438'
down_revision: Union[str, None] = '81289a9455e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_methods', sa.JSON(), nullable=True),
    sa.Column('login_notifications', sa.Boolean(), nullable=True),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_transaction_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_confirmation', sa.Boolean(), nullable=True),
    sa.Column('p2p_enabled', sa.Boolean(), nullable=True),
    sa.Column('p2p_trade_notifications', sa.Boolean(), nullable=True),
    sa.Column('profile_visible', sa.Boolean(), nullable=True),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
