"""add transaction device and withdrawal authorization

Revision ID: 2e0bceb19713
Revises: a371b52dab8e
Create Date: 2026-10-02 02:06:48.890874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0bceb19713'
down_revision: Union[str, None] = 'a371b52dab8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_devices_device_id'), 'transaction_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_transaction_devices_id'), 'transaction_devices', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_devices_user_id'), 'transaction_devices', ['user_id'], unique=False)
    op.create_table('withdrawal_authorization_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('withdrawal_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('challenge_message', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['transaction_devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_authorization_challenges_device_id'), 'withdrawal_authorization_challenges', ['device_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_authorization_challenges_id'), 'withdrawal_authorization_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawal_authorization_challenges_nonce'), 'withdrawal_authorization_challenges', ['nonce'], unique=True)
    op.create_index(op.f('ix_withdrawal_authorization_challenges_user_id'), 'withdrawal_authorization_challenges', ['user_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_authorization_challenges_withdrawal_id'), 'withdrawal_authorization_challenges', ['withdrawal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_authorization_challenges_withdrawal_id'), table_name='withdrawal_authorization_challenges')
    op.drop_index(op.f('ix_withdrawal_authorization_challenges_user_id'), table_name='withdrawal_authorization_challenges')
    op.drop_index(op.f('ix_withdrawal_authorization_challenges_nonce'), table_name='withdrawal_authorization_challenges')
    op.drop_index(op.f('ix_withdrawal_authorization_challenges_id'), table_name='withdrawal_authorization_challenges')
    op.drop_index(op.f('ix_withdrawal_authorization_challenges_device_id'), table_name='withdrawal_authorization_challenges')
    op.drop_table('withdrawal_authorization_challenges')
    op.drop_index(op.f('ix_transaction_devices_user_id'), table_name='transaction_devices')
    op.drop_index(op.f('ix_transaction_devices_id'), table_name='transaction_devices')
    op.drop_index(op.f('ix_transaction_devices_device_id'), table_name='transaction_devices')
    op.drop_table('transaction_devices')
    # ### end Alembic commands ###
