"""Add wallets, ledger, transaction models

Revision ID: 34766b11cb5d
Revises: b88d782dd9b7
Create Date: 2026-02-20 00:33:57.819116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34766b11cb5d'
down_revision: Union[str, None] = 'b88d782dd9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
