"""methods

Revision ID: 37b278a6b4df
Revises: 514034990e7d
Create Date: 2026-09-26 19:59:34.429475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b278a6b4df'
down_revision: Union[str, None] = '514034990e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('authenticator_secret', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('email_2fa_verified', sa.Boolean(), nullable=False))
    op.add_column('settings', sa.Column('authenticator_2fa_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'authenticator_2fa_verified')
    op.drop_column('settings', 'email_2fa_verified')
    op.drop_column('settings', 'authenticator_secret')
    # ### end Alembic commands ###
