"""Initial migration for MySQL

Revision ID: 3cf79bf177ea
Revises: 
Create Date: 2025-09-29 13:39:35.969209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf79bf177ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('company_industry', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('verified_email', sa.Boolean(), nullable=True),
    sa.Column('subscription', sa.String(length=50), nullable=True),
    sa.Column('profile_pic', sa.String(length=225), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=225), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_companies_address'), 'companies', ['address'], unique=False)
    op.create_index(op.f('ix_companies_company_industry'), 'companies', ['company_industry'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=True)
    op.create_index(op.f('ix_companies_phone_number'), 'companies', ['phone_number'], unique=False)
    op.create_index(op.f('ix_companies_profile_pic'), 'companies', ['profile_pic'], unique=False)
    op.create_index(op.f('ix_companies_subscription'), 'companies', ['subscription'], unique=False)
    op.create_index(op.f('ix_companies_verified_email'), 'companies', ['verified_email'], unique=False)
    op.create_table('company_staffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('profile_pic', sa.String(length=225), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('accept_invitation', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=225), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_staffs_created_at'), 'company_staffs', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_staffs_department'), 'company_staffs', ['department'], unique=False)
    op.create_index(op.f('ix_company_staffs_email'), 'company_staffs', ['email'], unique=True)
    op.create_index(op.f('ix_company_staffs_full_name'), 'company_staffs', ['full_name'], unique=False)
    op.create_index(op.f('ix_company_staffs_id'), 'company_staffs', ['id'], unique=True)
    op.create_index(op.f('ix_company_staffs_is_active'), 'company_staffs', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_staffs_job_title'), 'company_staffs', ['job_title'], unique=False)
    op.create_index(op.f('ix_company_staffs_password'), 'company_staffs', ['password'], unique=False)
    op.create_index(op.f('ix_company_staffs_permissions'), 'company_staffs', ['permissions'], unique=False)
    op.create_index(op.f('ix_company_staffs_phone_number'), 'company_staffs', ['phone_number'], unique=False)
    op.create_index(op.f('ix_company_staffs_profile_pic'), 'company_staffs', ['profile_pic'], unique=False)
    op.create_index(op.f('ix_company_staffs_role'), 'company_staffs', ['role'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['company_staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_company_id'), 'attendance_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=True)
    op.create_index(op.f('ix_attendance_records_staff_id'), 'attendance_records', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_staff_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_company_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_company_staffs_role'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_profile_pic'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_phone_number'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_permissions'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_password'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_job_title'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_is_active'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_id'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_full_name'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_email'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_department'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_created_at'), table_name='company_staffs')
    op.drop_table('company_staffs')
    op.drop_index(op.f('ix_companies_verified_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_subscription'), table_name='companies')
    op.drop_index(op.f('ix_companies_profile_pic'), table_name='companies')
    op.drop_index(op.f('ix_companies_phone_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_address'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
