"""create tasks table

Revision ID: 5a162eca227f
Revises: ea144c2ee4a2
Create Date: 2025-10-17 13:46:36.397488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a162eca227f'
down_revision: Union[str, None] = 'ea144c2ee4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('pending', 'completed', 'overdue', name='taskstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
