"""create notification model

Revision ID: 68122704dc95
Revises: 37b278a6b4df
Create Date: 2026-09-29 20:36:38.341815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68122704dc95'
down_revision: Union[str, None] = '37b278a6b4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('kyc_tier', sa.Integer(), nullable=False),
    sa.Column('nin_verified', sa.Boolean(), nullable=False),
    sa.Column('bvn_verified', sa.Boolean(), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('document_verified', sa.Boolean(), nullable=False),
    sa.Column('liveness_verified', sa.Boolean(), nullable=False),
    sa.Column('face_verified', sa.Boolean(), nullable=False),
    sa.Column('aml_clear', sa.Boolean(), nullable=False),
    sa.Column('pep_match', sa.Boolean(), nullable=False),
    sa.Column('sanctions_match', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_column('settings', 'payment_confirmation')
    op.drop_column('settings', 'p2p_trade_notifications')
    op.drop_column('settings', 'daily_transaction_limit')
    op.drop_column('settings', 'biometric_enabled')
    op.drop_column('settings', 'login_notifications')
    op.drop_column('settings', 'push_notifications')
    op.drop_column('settings', 'p2p_enabled')
    op.drop_column('settings', 'analytics_enabled')
    op.drop_column('settings', 'sms_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('sms_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('analytics_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('p2p_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('push_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('login_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('biometric_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('daily_transaction_limit', mysql.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('settings', sa.Column('p2p_trade_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('payment_confirmation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('kyc_verifications')
    # ### end Alembic commands ###
