"""add transaction source and direction structures

Revision ID: 700a9d0806c8
Revises: f5da10bed0ff
Create Date: 2026-02-22 12:52:44.451279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700a9d0806c8'
down_revision: Union[str, None] = 'f5da10bed0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
