"""create products tables

Revision ID: 75de4d876b6e
Revises: e533e24ef8ba
Create Date: 2026-05-21 12:22:53.559599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75de4d876b6e'
down_revision: Union[str, None] = 'e533e24ef8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit_intents', 'flutterwave_bank_code')
    op.drop_column('deposit_intents', 'flutterwave_account_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_intents', sa.Column('flutterwave_account_number', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('deposit_intents', sa.Column('flutterwave_bank_code', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
