"""bal

Revision ID: 86d2e6c7f3d5
Revises: 15282bc0bc40
Create Date: 2026-02-14 03:23:11.956126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d2e6c7f3d5'
down_revision: Union[str, None] = '15282bc0bc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'balance')
    # ### end Alembic commands ###
