"""add token fields to companies

Revision ID: 9329e8b33056
Revises: d97be691f0ec
Create Date: 2025-06-18 10:37:02.230162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9329e8b33056'
down_revision: Union[str, None] = 'd97be691f0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('token', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'token_expires_at')
    op.drop_column('companies', 'token')
    # ### end Alembic commands ###
