"""creates

Revision ID: 9afd5677715a
Revises: 0108e21e1e83
Create Date: 2026-05-21 13:32:00.049859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9afd5677715a'
down_revision: Union[str, None] = '0108e21e1e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'from_amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'to_amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'to_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('transactions', 'from_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
