"""add model

Revision ID: a371b52dab8e
Revises: e7105ef0b87e
Create Date: 2026-10-01 13:30:19.546081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a371b52dab8e'
down_revision: Union[str, None] = 'e7105ef0b87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_pin_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_pin_history_user_id'), 'transaction_pin_history', ['user_id'], unique=False)
    op.add_column('kyc_verifications', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('transaction_pin_hash', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('transaction_pin_enabled', sa.Boolean(), nullable=False))
    op.add_column('settings', sa.Column('transaction_pin_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'transaction_pin_changed_at')
    op.drop_column('settings', 'transaction_pin_enabled')
    op.drop_column('settings', 'transaction_pin_hash')
    op.drop_column('kyc_verifications', 'external_id')
    op.drop_index(op.f('ix_transaction_pin_history_user_id'), table_name='transaction_pin_history')
    op.drop_table('transaction_pin_history')
    # ### end Alembic commands ###
