"""create swap table

Revision ID: aced5c811f12
Revises: 700a9d0806c8
Create Date: 2026-03-07 15:21:11.837013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aced5c811f12'
down_revision: Union[str, None] = '700a9d0806c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('min_rate', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', name='swapstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swap_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('swap_id', sa.String(length=36), nullable=False),
    sa.Column('taker_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=True),
    sa.Column('to_currency', sa.String(length=10), nullable=True),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['swap_id'], ['swaps.id'], ),
    sa.ForeignKeyConstraint(['taker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ledger_entries', 'amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
    op.add_column('wallets', sa.Column('locked_balance', sa.Numeric(precision=18, scale=8), nullable=True))
    op.alter_column('wallets', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=10),
               nullable=True)
    op.alter_column('wallets', 'balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'balance',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('wallets', 'currency',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=3),
               nullable=False)
    op.drop_column('wallets', 'locked_balance')
    op.alter_column('ledger_entries', 'amount',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_table('swap_executions')
    op.drop_table('swaps')
    # ### end Alembic commands ###
