"""fix varchar lengths for MySQL

Revision ID: b56cc88c6a15
Revises: fd65f33299e2
Create Date: 2026-03-27 20:57:46.766748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b56cc88c6a15'
down_revision: Union[str, None] = 'fd65f33299e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('min_amount', sa.Integer(), nullable=False))
    op.alter_column('wallets', 'locked_balance',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True,
               existing_server_default=sa.text('0.00000000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'locked_balance',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=False,
               existing_server_default=sa.text('0.00000000'))
    op.drop_column('swaps', 'min_amount')
    # ### end Alembic commands ###
