"""add accept_invitation field to CompanyStaffs

Revision ID: bd89d5c9e851
Revises: 674784020b5e
Create Date: 2025-07-22 16:04:31.392168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd89d5c9e851'
down_revision: Union[str, None] = '674784020b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_staffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accept_invitation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_staffs_created_at'), 'company_staffs', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_staffs_department'), 'company_staffs', ['department'], unique=False)
    op.create_index(op.f('ix_company_staffs_email'), 'company_staffs', ['email'], unique=True)
    op.create_index(op.f('ix_company_staffs_full_name'), 'company_staffs', ['full_name'], unique=False)
    op.create_index(op.f('ix_company_staffs_id'), 'company_staffs', ['id'], unique=True)
    op.create_index(op.f('ix_company_staffs_job_title'), 'company_staffs', ['job_title'], unique=False)
    op.create_index(op.f('ix_company_staffs_password'), 'company_staffs', ['password'], unique=False)
    op.create_index(op.f('ix_company_staffs_permissions'), 'company_staffs', ['permissions'], unique=False)
    op.create_index(op.f('ix_company_staffs_phone_number'), 'company_staffs', ['phone_number'], unique=False)
    op.create_index(op.f('ix_company_staffs_profile_pic'), 'company_staffs', ['profile_pic'], unique=False)
    op.create_index(op.f('ix_company_staffs_role'), 'company_staffs', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_staffs_role'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_profile_pic'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_phone_number'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_permissions'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_password'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_job_title'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_id'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_full_name'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_email'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_department'), table_name='company_staffs')
    op.drop_index(op.f('ix_company_staffs_created_at'), table_name='company_staffs')
    op.drop_table('company_staffs')
    # ### end Alembic commands ###
