"""added toke field migration

Revision ID: d6686eb17d45
Revises: bd89d5c9e851
Create Date: 2025-08-03 16:24:44.583330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6686eb17d45'
down_revision: Union[str, None] = 'bd89d5c9e851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_staffs', sa.Column('token', sa.String(), nullable=True))
    op.add_column('company_staffs', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_staffs', 'token_expires_at')
    op.drop_column('company_staffs', 'token')
    # ### end Alembic commands ###
