"""create products tabless

Revision ID: e533e24ef8ba
Revises: d46f39b025bf
Create Date: 2026-05-21 09:22:52.974667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e533e24ef8ba'
down_revision: Union[str, None] = 'd46f39b025bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_country_code'), 'users', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country_code'), table_name='users')
    op.drop_column('users', 'country_code')
    # ### end Alembic commands ###
