"""create tasks table

Revision ID: ea144c2ee4a2
Revises: 3cf79bf177ea
Create Date: 2025-10-17 13:32:07.173171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea144c2ee4a2'
down_revision: Union[str, None] = '3cf79bf177ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('task_title', sa.String(length=150), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('priority', sa.Enum('IMPORTANT', 'NORMAL', 'LOW', name='taskpriority'), nullable=False),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['company_staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_customer_name'), 'tasks', ['customer_name'], unique=False)
    op.create_index(op.f('ix_tasks_customer_phone'), 'tasks', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_tasks_date'), 'tasks', ['date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=True)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_staff_id'), 'tasks', ['staff_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_title'), 'tasks', ['task_title'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_time'), 'tasks', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_time'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_staff_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_customer_phone'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_customer_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
