"""added toke field migration

Revision ID: f922c909928e
Revises: d6686eb17d45
Create Date: 2025-08-03 16:36:57.468659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f922c909928e'
down_revision: Union[str, None] = 'd6686eb17d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('active', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'active')
    # ### end Alembic commands ###
